version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bot-presenciales-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bot-presenciales
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot_network

  flask:
    build: .
    container_name: bot-presenciales-app
    command: >
      sh -c "./migrate.sh && flask run --host=0.0.0.0"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:1234@postgres:5432/bot-presenciales
    depends_on:
      - postgres
    networks:
      - bot_network
    volumes:
      - .:/app

networks:
  bot_network:
    driver: bridge

volumes:
  postgres_data:
